sudo: required
services:
- docker
env:
  global:
  - REGISTRY_USER=travisbot
  - BRANCH=${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH}
  - REPO=baileybase/embed_dependencies
  - secure: feZsBedC/8UZgvWlyVTFmRREeR7o7/htXTs+UkmSHa6cQp8UtTOAUClRcuRwkrIFLhVx+b7mrjrHhSHGiYJKoah3GQQ7nMaCItleVF2UTdi+PMhIjlEieYhv0FBoA+qfZcypteGHJLe/g3sp7mcABQ8/MDlZtk6adRnS4MkyOwTnOm3qANhj3I5fKQUThJUaoN7Hiv5cE3uR7xfYE0z60dK6CCNmF+dfat0c0Vi/q45QQp/+3TfLoBpTghNEwyNsSZ3MsXlJrz2TFlAQa9cir0A0M3z+5IK58ABU9m72AvD2xBvG79bkLqmh/MPrhCVtO44yTZzkUnrrYcAbP8sE8tzyuCrJvtqKivnArd92/d+kn/tCCqkX1KZNd/7KqcuAyX5vowlneQ6f12ocytzvb7kLjAfYsnZf8iUxHQdPqc7dZ1czqfn4jVkWmuMTDedcF4D+svKBtf8sxRbWaOvzScreRgYKCX01fLNl+acWzdjf3DdKt5cHA2SpEkBauWpRh9GCHGTBMIjh7Ovv+MkrLhQSzqU3coyyWKJUb89CA17DzXIQ16jG60uKiJfXRDfXuIZT+0y8m0JDR17H9r/27R16cpijAAsKq+QXf961GXqmCw+TABtRr0L2x3YXDWkz0bcP8nBS/hlghN+U9VAqxTlulJZT+o6v8neA9taKbeE=

notifications:
  slack:
    secure: qk4+aFW5R2/0fqaAz1tzpxSvDdDkRqJHEPdNUuHSSYZ66aJG6nu8y/oF8nLNos+ypk1bNbt51EKXfGrom73REB49m13zVUvpd2ZNYLVsF9z/NKr9pelwzl6+gnfu/Ku8GhELKKHp3HQSQFGpUKB0su9X5mgpOCH7lb5vpuDU/SU1TPp2UL5tzHoXbu66r6ptELUnD/9zctttAIZeeJJ5iwEjkCnKxxUVkT1+aZZAuwSfd65cEV6Q8Dxj2Cs1XENrkzJfaGyeryd5mxiFDm5f5mSE0pDR6l7Vk+yvoQ+fn+eBFxAWuC7dQM+paEncMXLERp9S+YPg5AbA0l5jvRV7LSCC0cuShy1bONZu2rjwW+oCnsDAdfE8gVyEyi2wUX3/0XP8GeTlZ7DAH3s1t28H0CIkvk8niRcl/Lmktk7Wnme63KrSaIkbzMDRj4HguheMn6PbA+IGp86aGuCWHGHRVdXaH1GepuL9bSeskO9+Bp7tffvp0QP+o4fqQzQ5SdyQ6KsdZifmzxpv1sR+Es3y5lTqkR2rpTkEP6AmlOVFUd8kT254pZIlRJIetsloazJ9o4gujCVnai5AsgIfbNcLNAvcD5blsSdMP9T55/KkwYf7f9LBa8NfLhz/bLJ2htcto+AWdxyr79T6ZwExTCMfGXxhJNnVfyO2O4i3XqgVFbM=

jobs:
  include:
  - os: linux
    dist: bionic
before_install:
- curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
- sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu
  $(lsb_release -cs) stable"
- sudo apt-get update
- sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
- echo '{"features":{ "buildkit":true },"experimental":true}'  | sudo tee /etc/docker/daemon.json
- sudo service docker restart
- if [ "${BRANCH}" = "master" ]; then export BRANCH="latest"; else echo "Strings are
  not equal."; fi
- echo BRANCH "$BRANCH"
before_script:
- docker --version
- docker version -f '{{.Server.Experimental}}'
- docker pull $REPO || true
script:
#  embed base image
- cp embed_dependencies/Dockerfile .
- export DOCKER_BUILDKIT=1
- docker build --progress=plain --pull --cache-from $REPO:$BRANCH --tag $REPO:$BRANCH .
- docker run $REPO:$BRANCH
- rm Dockerfile
before_deploy:
- echo "$REGISTRY_PASS" | docker login --username $REGISTRY_USER --password-stdin
deploy:
  provider: script
  script: docker push $REPO:$BRANCH
  on:
    all_branches: true
